### PR TITLE
Upversion to 0.3.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by rgrunber**
- Restore tag references to ${project.version}

Signed-off-by: Roland Grunberg <rgrunber@redhat.com>

### CODE REVIEW

**Comment by rgrunber** [comment]
@angelozerr @datho7561 . Are we fine with 0.3.0-SNAPSHOT. Do we expect a 0.2.2 type release at all ?

**Comment by datho7561** [comment]
I think 0.3.0 makes sense

**Comment by angelozerr** [comment]
>Do we expect a 0.2.2 type release at all ?

No I think we can merge your PR.

**Comment by rgrunber** [comment]
@fbricon @angelozerr , feel free to merge (I haven't got commit rights).

**Pull request merged**
