### PR TITLE
Use template to determine jakarta namespace in snippets

### LINKED ISSUE #229: Add support for jakarta namespace
MP 5 supports jakarta namespace aligning with Jakarta EE 9/9.1.  The LS should support the use of packages with the jakarta namespace.

Cc @kathrynkodama

### LINKED ISSUE #320: Snippets using Java EE 8 when project is using Jakarta EE9+
For example, the `mpreadiness` snippet will be filtered on the context `org.eclipse.microprofile.health.Readiness` but there isn't additional filtering to check the EE version. So if I am using EE9, the jaxrs namespace will still be inserted via the snippet even though my project is using EE9 with the jakarta.x namespace. 

image

### PR DESCRIPTION
**Pull request by datho7561**
- Use `${jakarta}` to point to either `javax` or `jakarta`, depending on which is available, and prefering `jakarta`
- Rename `jaxrc` to `rest_class` and `jaxrm` to `rest_get`

Closes #320, closes #229

Signed-off-by: David Thompson <davthomp@redhat.com>

### CODE REVIEW

**Comment by datho7561** [comment]
Sorry, this is broken, I need to fix it

**Comment by angelozerr** [comment]
It works like a charm,thanks @datho7561 !

**Comment by angelozerr** [comment]
@kathrynkodama @yeekangc please at look at this merged PR, now we can support jakarta/javax namespace with the same snippet.

**Comment by kathrynkodama** [comment]
@angelozerr @datho7561 thank you! This is excellent

**Pull request merged**
