### PR TITLE
Use `computeModelAsyncCompose` from quarkus-ls

### LINKED ISSUE #257: Copy over `ModelTextDocuments#computeModelAsyncCompose` from quarkus-ls into commons package
See https://github.com/redhat-developer/quarkus-ls/pull/659/files?w=1#diff-8ffdd77369ed4ef0561d74cd65bfffd95327217e65143805720c33a137b991dd

This helper method is very helpful when implementing the `TextDocumentService` for an lsp4j-based language server, so it makes sense to include in the commons package.

### PR DESCRIPTION
**Pull request by datho7561**
This method makes it easier to implement go to definition in properties files. Includes the recent bug fix to the method (see redhat-developer/quarkus-ls#679)

Closes #257

Signed-off-by: David Thompson <davthomp@redhat.com>

### CODE REVIEW

**Comment by angelozerr** [comment]
I think we should do the same thing in https://github.com/eclipse/lsp4mp/blob/4adecbd009fdff3d53293fcf92bea7c318108244/microprofile.ls/org.eclipse.lsp4mp.ls/src/main/java/org/eclipse/lsp4mp/ls/java/JavaTextDocuments.java#L130 no?

**Comment by datho7561** [comment]
Good catch!

**Comment by datho7561** [comment]
@angelozerr if you have some time, could you please take a look at this PR?

**Comment by angelozerr** [comment]
LGTM, thanks @datho7561 !

**Pull request merged**
