### PR TITLE
NPE during textDocument/definition

### LINKED ISSUE #372: NPE during textDocument/definition
I was not able to reproduce it, but at some point I ctrl+clicked on my application.properties and saw an error popup n VS Code. Stacktrace shows:

```
SEVERE: Internal error: java.lang.NullPointerException: Cannot invoke "org.eclipse.lsp4mp.commons.MicroProfileProjectInfo.getProperties()" because "info" is null
java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "org.eclipse.lsp4mp.commons.MicroProfileProjectInfo.getProperties()" because "info" is null
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.NullPointerException: Cannot invoke "org.eclipse.lsp4mp.commons.MicroProfileProjectInfo.getProperties()" because "info" is null
	at org.eclipse.lsp4mp.utils.PropertiesFileUtils.getProperty(PropertiesFileUtils.java:184)
	at org.eclipse.lsp4mp.services.properties.PropertiesFileDefinition.findDefinition(PropertiesFileDefinition.java:98)
	at org.eclipse.lsp4mp.services.properties.PropertiesFileLanguageService.findDefinition(PropertiesFileLanguageService.java:156)
	at org.eclipse.lsp4mp.ls.properties.PropertiesFileTextDocumentService.lambda$definition$7(PropertiesFileTextDocumentService.java:196)
	at org.eclipse.lsp4mp.ls.commons.ModelTextDocuments.lambda$computeModelAsyncCompose$1(ModelTextDocuments.java:146)
	... 7 more

[Error - 18:28:21] Request textDocument/definition failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "org.eclipse.lsp4mp.commons.MicroProfileProjectInfo.getProperties()" because "info" is null
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.NullPointerException: Cannot invoke "org.eclipse.lsp4mp.commons.MicroProfileProjectInfo.getProperties()" because "info" is null
	at org.eclipse.lsp4mp.utils.PropertiesFileUtils.getProperty(PropertiesFileUtils.java:184)
	at org.eclipse.lsp4mp.services.properties.PropertiesFileDefinition.findDefinition(PropertiesFileDefinition.java:98)
	at org.eclipse.lsp4mp.services.properties.PropertiesFileLanguageService.findDefinition(PropertiesFileLanguageService.java:156)
	at org.eclipse.lsp4mp.ls.properties.PropertiesFileTextDocumentService.lambda$definition$7(PropertiesFileTextDocumentService.java:196)
	at org.eclipse.lsp4mp.ls.commons.ModelTextDocuments.lambda$computeModelAsyncCompose$1(ModelTextDocuments.java:146)
	... 7 more

```

This is using the latest vscode-microprofile pre-release build (v0.7.2023031404)

### PR DESCRIPTION
**Pull request by angelozerr**
NPE during textDocument/definition

Fixes #372

### CODE REVIEW

**Comment by datho7561** [comment]
This is not the root cause of the issue, I'm pretty sure the problem is that we need to wait for jdt.ls to start in vscode-microprofile before issuing delegate commands to it. You can see that hover will also NPE if you open a `{application,microprofile-config}.properties` and start hovering things before jdt.ls loads.

**Comment by datho7561** [comment]
Nevermind, I looked at the vscode-microprofile client-side code, and we are already waiting for jdt.ls to start before issuing the delegate commands. I guess the issue is that the project info is not loaded before running the other delegate command, and this PR will address this.

**Comment by angelozerr** [comment]
>  I guess the issue is that the project info is not loaded before running the other delegate command, and this PR will address this.

Indeed it was the idea. But for hover have you the similar problem? We check in language server if project info is different from null to process hover from the language service.

**Comment by datho7561** [comment]
I tried this PR again. If I open a properties file and move the cursor around while holding `Ctrl`, then sometimes definition fails, even with this PR. The failure message I get is:

```
[Trace - 13:26:14] Received response 'textDocument/definition - (67)' in 49ms. Request failed: Request microprofile/propertyDefinition failed with message: 1234 [in ConfigurationType [in ConfigurationType.java [in org.acme [in src/main/java [in quarkius]]]]] does not exist (-32603).
```

But, the file and class mentioned in the message exists. I don't get a stack trace.

**Comment by angelozerr** [comment]
> But, the file and class mentioned in the message exists. I don't get a stack trace.

I think it is an another issue?

**Comment by datho7561** [comment]
You're right. It's a separate problem, I'll create a new issue.

**Review by datho7561 — APPROVED** [review]
Alright, this fixes the issue for me. Thanks, Angelo!

**Comment by datho7561** [comment]
Hover is also a slightly different issue. I'll open a separate issue for that.

**Pull request merged**
