### PR TITLE
Binary dynamic properties should generate properties after an update

### PR DESCRIPTION
**Pull request by angelozerr**
Binary dynamic properties should generate properties after an update

Signed-off-by: azerr <azerr@redhat.com>

### CODE REVIEW

**Comment by angelozerr** [comment]
I need to write more tests.

**Comment by datho7561** [comment]
I am planning on reviewing this

**Review by datho7561 — APPROVED** [review]

**Comment by datho7561** [comment]
The tests don't fail on my computer

**Comment by angelozerr** [comment]
> The tests don't fail on my computer

I restarted the job, tests is working.

**Review by rgrunber — APPROVED** [review]
Change looks good to me and seems to be working.

**Pull request merged**
