### PR TITLE
Changelog for 0.6.0

### PR DESCRIPTION
**Pull request by rgrunber**
Signed-off-by: Roland Grunberg <rgrunber@redhat.com>

### CODE REVIEW

**Comment by rgrunber** [comment]
We should merge once we're sure all necessary changes are in.

**Review by datho7561 — CHANGES_REQUESTED** [review]
Two small notes, otherwise looks pretty good

**Comment by datho7561** [comment]
I think all the JAX-RS related feature should wait until the next release. What do you think about https://github.com/eclipse/lsp4mp/issues/304, should I try to fix that for this release?

**Comment by rgrunber** [comment]
> I think all the JAX-RS related feature should wait until the next release. What do you think about #304, should I try to fix that for this release?

If you have time to address it, makes sense to do it.

**Comment by datho7561** [comment]
I'll take a look at it now, if it's a small fix, I'll let you know

**Review by datho7561 — APPROVED** [review]
Looks good!

**Review by datho7561 — APPROVED** [review]
Looks good to me. Thanks, Roland!

**Pull request merged**
