### PR TITLE
Update eclipse.jdt.ls to 1.20.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by datho7561**
Signed-off-by: David Thompson <davthomp@redhat.com>

### CODE REVIEW

**Review by rgrunber — APPROVED** [review]
There are some infra issues at Eclipse, but the change looks fine to me.

`org.eclipse.jdt.ls.tp @ ${jdt.ls.version}` will get the version of the JDT-LS target platform. This will **NOT** include `org.eclipse.jdt.s.core` . That comes from https://download.eclipse.org/jdtls/snapshots/repository/latest/ . So this just ensures that we use the proper dependencies.

**Comment by datho7561** [comment]
Okay. Do you think it makes sense to wait on the infrastructure to be back up before merging this?

**Comment by rgrunber** [comment]
Sure, we can wait, and monitor on https://www.eclipsestatus.io/incidents/j724xpdbz3sb & https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2549

**Comment by angelozerr** [comment]
Thanks @datho7561 !

**Pull request merged**
