### PR TITLE
Fix inlay hint + definition when project returns empty properties.

### PR DESCRIPTION
**Pull request by angelozerr**
Fix inlay hint + definition when project returns empty properties.

Signed-off-by: azerr <azerr@redhat.com>

### CODE REVIEW

**Comment by angelozerr** [comment]
I have written test for inlay hint. 

I need to write test for definition now.

**Comment by angelozerr** [comment]
It should be good now.

**Review by datho7561 — APPROVED** [review]
Looks good! I can't think of a way to test this manually, since even in non-microprofile projects the `config_ordinal` property is present (this is a bug, I think it should depend on microprofile-config being present).

**Comment by datho7561** [comment]
See #312

**Pull request merged**
