### PR TITLE
Check for `HealthCheck` instead of `Health` before validation

### LINKED ISSUE #314: MicroProfileHealthDiagnosticsParticipant incompatible with MicroProfile Health 3.0 and later
https://github.com/eclipse/lsp4mp/blob/2d7d129f545151f123ff935893a0853959164d34/microprofile.jdt/org.eclipse.lsp4mp.jdt.core/src/main/java/org/eclipse/lsp4mp/jdt/internal/health/java/MicroProfileHealthDiagnosticsParticipant.java#L75

### PR DESCRIPTION
**Pull request by datho7561**
Check to make sure that `HealthCheck` is on the classpath before before performing the microprofile-health specific validations. Health was removed in microprofile-health 3.0.

Fixes #314

Signed-off-by: David Thompson <davthomp@redhat.com>

### CODE REVIEW

**Comment by datho7561** [comment]
I tested against the OpenLiberty project from [my other PR](https://github.com/eclipse/lsp4mp/pull/313), which has microprofile-health 3.0, and I can get the diagnostic to appear there.

**Comment by datho7561** [comment]
Good catch! I'll add that in

**Comment by JessicaJHee** [comment]
Looks good to me! One thing I was wondering was that should we be checking for `HealthCheck` instead of `Health` here as well? https://github.com/eclipse/lsp4mp/blob/9789a1a996811fade43029605c014c7825e8f1da/microprofile.jdt/org.eclipse.lsp4mp.jdt.core/src/main/java/org/eclipse/lsp4mp/jdt/internal/health/java/MicroProfileHealthDiagnosticsParticipant.java#L114

**Comment by datho7561** [comment]
In addition to fixing the code actions, I fixed the wording of the error message based on if `@Health` is present.

**Comment by rgrunber** [comment]
I would also look into the failure at https://github.com/eclipse/lsp4mp/blob/167d09e9979acd2418b86be60380dfeb2a55c589/microprofile.jdt/org.eclipse.lsp4mp.jdt.core/src/main/java/org/eclipse/lsp4mp/jdt/core/java/codeaction/InsertAnnotationMissingQuickFix.java#L93 . I don't think it's related to this change, but I noticed the code actions don't work for me.

<details>
<summary>stacktrace</summary>

```
[Error - 12:54:58 p.m.] Nov. 16, 2022, 12:54:58 p.m. Error in calling delegate command handler
class java.util.ArrayList cannot be cast to class [Ljava.lang.String; (java.util.ArrayList and [Ljava.lang.String; are in module java.base of loader 'bootstrap')
java.lang.ClassCastException: class java.util.ArrayList cannot be cast to class [Ljava.lang.String; (java.util.ArrayList and [Ljava.lang.String; are in module java.base of loader 'bootstrap')
	at org.eclipse.lsp4mp.jdt.core.java.codeaction.InsertAnnotationMissingQuickFix.resolveCodeAction(InsertAnnotationMissingQuickFix.java:93)
	at org.eclipse.lsp4mp.jdt.internal.core.java.codeaction.JavaCodeActionDefinition.resolveCodeAction(JavaCodeActionDefinition.java:93)
	at org.eclipse.lsp4mp.jdt.internal.core.java.codeaction.CodeActionHandler.resolveCodeAction(CodeActionHandler.java:203)
```
</details>

**Comment by datho7561** [comment]
> I would also look into the failure at

Good catch, I'll fix this

**Comment by datho7561** [comment]
Okay, should be fixed.

**Review by rgrunber — APPROVED** [review]
Works for me now. Feel free to merge when ready.

**Comment by datho7561** [comment]
Thanks, the `.project` was `.gitignore`d.

**Review by rgrunber — APPROVED** [review]

**Pull request merged**
