### PR TITLE
Require Java 11 to build and run

### LINKED ISSUE #12: Require Java 11 to build/run
jdt.ls is moving to Java 11 as a minimum requirement, so let's do the same, or we'll run into some serious headaches.
See https://github.com/eclipse/eclipse.jdt.ls/pull/1509

### PR DESCRIPTION
**Pull request by datho7561**
Closes #12.

Signed-off-by: David Thompson <davthomp@redhat.com>

### CODE REVIEW

**Comment by datho7561** [comment]
The build fails, since Jenkins is currently set to compile with JDK 8.

**Comment by fbricon** [comment]
It's because Jenkins doesn't trust you:

```
Loading trusted files from base branch master at 82c4798ac142efeb06499ece053407ef01009d46 rather than 4502c64638434c6cc47e66c16948792f008db4f0
Obtained Jenkinsfile from 82c4798ac142efeb06499ece053407ef01009d46
‘Jenkinsfile’ has been modified in an untrusted revision
```

**Comment by datho7561** [comment]
> It's because Jenkins doesn't trust you:

Okay. That makes sense. Does this mean that you will have to author the PR (or co-author or something)?

**Comment by fbricon** [comment]
Merged to allow building pending PRs

**Pull request merged**
