### PR TITLE
Update file headers to use EPL 2.0

### LINKED ISSUE #53: Update file headers to use EPL 2.0
Update all necessary file headers to use the license that is selected for the project.

e.g.

 * This program and the accompanying materials are made available under the 2
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.

### PR DESCRIPTION
**Pull request by angelozerr**
Update file headers to use EPL 2.0

Fixes #53

Signed-off-by: azerr <azerr@redhat.com>

### CODE REVIEW

**Comment by yeekangc** [comment]
Thank you, @angelozerr!

**Comment by fbricon** [comment]
Got a comment from Sharon:

> The project headers need to be addressed before accepting external
> contributions to ensure contributors are aware of the project license.
> 
> As Shawn identified the copyright and license header for the project code is:
> 
> /********************************************************************************
>  * Copyright (c) {date} {owner}[ and others]
>  *
>  * This program and the accompanying materials are made available under the
>  * terms of the Eclipse Public License v. 2.0 which is available at
>  * http://www.eclipse.org/legal/epl-2.0, or the Apache License, Version 2.0
>  * which is available at https://www.apache.org/licenses/LICENSE-2.0.
>  *
>  * SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
> 
> ********************************************************************************/
> 
> Content that may have been used from other Eclipse projects or third party
> content included should remain under their respective licenses.  Exception to
> that is if you used content from an Eclipse project that is EPL-1.0, you can
> rev the license header to EPL-2.0.
> 
> Regarding accepting external contributions, please address the header issue
> first to ensure there is no confusion about what license applies to content
> being contributed especially in light of the fact the only license visible on
> the repo is the EPL.
>

**Comment by fbricon** [comment]
Also see https://www.eclipse.org/projects/tools/documentation.php?id=technology.lsp4mp

**Comment by fbricon** [comment]
Superseded by #57

**Pull request closed without merging**
