### PR TITLE
Use `JavadocContentAccess2`

### LINKED ISSUE #297: Use `JavadocContentAccess2` for better Markdown hover documentation
eclipse.jdt.ls makes use of `JavadocContentAccess2` to provide its Markdown-formatted hover documentation ([here is its use in the hover implementation](https://github.com/eclipse/eclipse.jdt.ls/blob/c15fe895fdc3eaca1386ff1cebde36f3af63f733/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/HoverInfoProvider.java#L311)). It would be nice to use the same method in JDTUtilsLSImpl.

### PR DESCRIPTION
**Pull request by datho7561**
Closes #297

Signed-off-by: David Thompson <davthomp@redhat.com>

### CODE REVIEW

**Comment by rgrunber** [comment]
Would just be good to have an idea of what regresses as a result of this and what we gain.

**Comment by datho7561** [comment]
I think I might need to investigate further. When I use `JavadocContentAccess2`, the `{@link` tags try to point to `jdt://` for references to binary classes, which doesn't end up as a link in the vscode UI for some reason. I don't know why the test here doesn't reflect that, though.

**Comment by datho7561** [comment]
See https://github.com/redhat-developer/vscode-java/issues/2810. I'll add a test here that demonstrates that `JavadocContentAccess2` generally gives better hover documentation results.

**Comment by rgrunber** [comment]
Good catch on the javadoc extraction.

**Comment by rgrunber** [comment]
Looks like this is causing https://ci.eclipse.org/lsp4mp/job/lsp4mp/job/master/186/testReport/org.eclipse.lsp4mp.jdt.core.faulttolerance.properties/MicroProfileFaultTolerancePropertiesTest/Build_LSP4MP_JDT_LS_extension___microprofileFaultTolerancePropertiesTest/ but worked for me locally.

**Pull request merged**
